### ISSUE TITLE
Process exits when trying to open any text file on editor

### ISSUE THREAD

**Issue by zoedsoupe** [sayanarijit/xplr#671]
How xplr knows about which editor to use? From the `$EDITOR` env var? If so, I set `$EDITOR` to `”hx”` but when trying to open with `:e` I receive the followinf error:

```
17:46:39|ERROR) process exited with code exit status: 101
```

video to demonstrate:

https://github.com/sayanarijit/xplr/assets/44469426/1ac17ed2-0797-4146-ae11-cad8ab14c3c9

- version: `0.21.3`
- installation: via `nix` with `home-manager`

**Comment by zoedsoupe** [comment]
Ok, I tried to use other editors and it seems to only have errors with the Helix editor. Neovim, nano, Vim and etc works fine.

**Comment by zoedsoupe** [comment]
Tried to use the last helix [commit](https://github.com/helix-editor/helix/commit/a8574805617d86304232b47d84fd7c7f4f773520) but nows it fails with code `127` 🤔

**Comment by sayanarijit** [comment]
I can't reproduce the same on Linux. To see the actual error, and debug things, open xplr shell (`:!`) and try to run helix from the shell.

**Comment by zoedsoupe** [comment]
the actual error executing from shell is:
```sh
thread 'main' panicked at 'reader source not set', /private/tmp/nix-build-helix-23.05.drv-0/helix-23.05-vendor.tar.gz/crossterm/src/event/read.rs:38:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And the complete backtrace is:
```
thread 'main' panicked at 'reader source not set', thread 'main' panicked at 'reader source not set', /private/tmp/nix-build-helix-23.05.drv-0/helix-23.05-vendor.tar.gz/crossterm/src/event/read.rs:38:30
stack backtrace:
/private/tmp/nix-build-helix-23.05.drv-0/helix-23.05-vendor.tar.gz/crossterm/src/event/read.rs:38:30
stack backtrace:
   0:        0x104ec650c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h720a11e45da4bbbb
   0:        0x104ec650c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h720a11e45da4bbbb
   1   1:       :        0x1046678f4 - core:: 0x1046678f4 - core::fmt::write::hbe685eff0aa6c43c
fmt::write::hbe685eff0aa6c43c
   2:      2:        0x104eb69d0 - std::io::Write::write_fmt::hc2dfd4fbc57e25d0
     0x104eb69d0 - std::io::Write::write_fmt::hc2dfd4fbc57e25d0
   3:        3:        0x104ec6320 - std::sys_common::   0x104ec6320 - std::sys_common::backtrace::print::h7a4c906fbb654184
backtrace::print::h7a4c906fbb654184
   4:      4:             0x104eb79e4 - std::panicking::default_hook::0x104eb79e4 - std::panicking::default_hook::{{closure}}::h2610a2e7cb8dbcf5
{{closure}}::h2610a2e7cb8dbcf5
   5:    5:        0x104eb7774       0x104eb7774 - std::panicking::default_hook::h639d82104fd456f7
 - std::panicking::default_hook::h639d82104fd456f7
   6:      6:        0x104eb7f20 - std::     0x104eb7f20 - std::panicking::rust_panic_with_hook::h69fe702765c523f3
 panicking::rust_panic_with_hook::h69fe702765c523f3
   7:        7:        0x104ec6d70 - std::panicking::  0x104ec6d70 - std::panicking::begin_panic_handler::{{closure}}::ha232e020ee1923bebegin_panic_handler::{{closure}}::ha232e020ee1923be
   8:  
   8:             0x104ec65f8 - std:: 0x104ec65f8 - std::sys_common::backtrace::__rust_end_short_backtrace::hbab87f1d75b19d5d
sys_common::backtrace::__rust_end_short_backtrace::hbab87f1d75b19d5d
   9:       9:        0x104eb7b54 - _rust_begin_unwind
    0x104eb7b54 - _rust_begin_unwind
  10:      10:        0x104f8a78c - core::panicking::panic_fmt::    0x104f8a78c - core::panicking::panic_fmt::hba11916802e6d621
  11:   hba11916802e6d621
  11:        0x104f8a704 - core     0x104f8a704 - core::option::expect_failed::h42bc450e7f4b2e52
::option::expect_failed::h42bc450e7f4b2e52
  12  12:        0x104684f5c:        0x104684f5c - <crossterm::event::stream::EventStream - <crossterm::event::stream::EventStream as core::default::Default> as core::default::Default>::default::h1c4dee14c774706f
::default::h1c4dee14c774706f
  13:   13:        0x104d1f27c -        0x104d1f27c - tokio::tokio::runtime::park::CachedParkThread::block_on::h1a34e747a61a1ea5runtime::park::CachedParkThread::block_on::h1a34e747a61a1ea5

  14:   14:        0x104d418b8       0x104d418b8 - tokio::runtime - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::::scheduler::multi_thread::MultiThread::block_on::hd1829ea03429f511
hd1829ea03429f511
  15  15:     :        0x104d50820 - tokio::runtime   0x104d50820 - tokio::runtime::runtime::Runtime::block_on::h4fbf95286efa82d1
::runtime::Runtime::block_on::h4fbf95286efa82d1
  16  16:        0x104d34914:        0x104d34914 - hx::main::hf39368c4f38ba401
 - hx::main::hf39368c4f38ba401
  17:      17:        0x104d4215c - std::    0x104d4215c - std::sys_common::backtrace::__rust_begin_short_backtrace::h3ec1aac8877973b5
sys_common::backtrace::__rust_begin_short_backtrace::h3ec1aac8877973b5
  18:      18:        0x104d49524 - std::    0x104d49524 - std::rt::lang_start::{{closure}rt::lang_start::{{closure}}::h6d453483a7c62a09
  }::h6d453483a7c62a09
  19:        19:        0x104eb5e64 - std::rt::lang_start_internal::0x104eb5e64 - std::rt::lang_start_internal::ha3541e17cd112a19
  20: ha3541e17cd112a19
  20:             0x104d34a10 - _main
  0x104d34a10 - _main
```

**Comment by zoedsoupe** [comment]
oh, sorry to not give an update, but no, this isn't anymore an issue! i don't know exactly when/how this was solved tho...
